export default [
    { name: "الجزائر الوسطى", price: 500 },
    { name: "سيدي امحمد", price: 500 },
    { name: "المدنية", price: 400 },
    { name: "المرادية", price: 400 },
    { name: "باب الوادي", price: 500 },
    { name: "بولوغين", price: 500 },
    { name: "القصبة", price: 500 },
    { name: "وادي قريش", price: 500 },
    { name: "بئر مراد رايس", price: 400 },
    { name: "الأبيار", price: 500 },
    { name: "بوزريعة", price: 600 },
    { name: "بئر خادم", price: 400 },
    { name: "الحراش", price: 350 },
    { name: "براقي", price: 300 },
    { name: "وادي السمار", price: 350 },
    { name: "بوروبة", price: 350 },
    { name: "حسين داي", price: 400 },
    { name: "القبة", price: 400 },
    { name: "باش جراح", price: 350 },
    { name: "الدار البيضاء", price: 400 },
    { name: "باب الزوار", price: 400 },
    { name: "بن عكنون", price: 400 },
    { name: "دالي إبراهيم", price: 500 },
    { name: "الحمامات", price: 700 },
    { name: "الرايس حميدو", price: 700 },
    { name: "جسر قسنطينة", price: 350 },
    { name: "حيدرة", price: 400 },
    { name: "المحمدية", price: 400 },
    { name: "برج الكيفان", price: 400 },
    { name: "المقارية", price: 400 },
    { name: "بني مسوس", price: 500 },
    { name: "الكاليتوس", price: 350 },
    { name: "تسالة المرجة", price: 400 },
    { name: "أولاد شبل", price: 400 },
    { name: "بئر توتة", price: 400 },
    { name: "سيدي موسى", price: 350 },
    { name: "الرويبة", price: 500 },
    { name: "هراوة", price: 700 },
    { name: "الرغاية", price: 600 },
    { name: "عين طاية", price: 700 },
    { name: "الخرايسية", price: 400 },
    { name: "برج البحري", price: 600 },
    { name: "المرسى", price: 700 },
    { name: "زرالدة", price: 700 },
    { name: "السحاولة", price: 400 },
    { name: "المعالمة", price: 700 },
    { name: "بابا حسن", price: 500 },
    { name: "الدويرة", price: 500 },
    { name: "الدرارية", price: 600 },
    { name: "الرحمانية", price: 700 },
    { name: "أولاد فايت", price: 600 },
    { name: "الشراقة", price: 500 },
    { name: "سطاوالي", price: 700 },
    { name: "العاشور", price: 500 },
    { name: "السويدانية", price: 700 },
    { name: "عين البنيان", price: 700 },
];

